services:
  - type: web
    name: nuha-ai-service
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:10000"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
